# Create Pandas Series

In [13]:
import pandas as pd

In [15]:
a = pd.Series([1,2,3,4,5])

In [17]:
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [19]:
type(a)

pandas.core.series.Series

In [21]:
a = pd.date_range(start="01-01-2018", end="23-5-2018")

In [23]:
a

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08',
               '2018-01-09', '2018-01-10',
               ...
               '2018-05-14', '2018-05-15', '2018-05-16', '2018-05-17',
               '2018-05-18', '2018-05-19', '2018-05-20', '2018-05-21',
               '2018-05-22', '2018-05-23'],
              dtype='datetime64[ns]', length=143, freq='D')

# Create Pandas DataFrame

In [26]:
import numpy as np

In [28]:
temp = np.random.randint(low=20, high=100, size=20)

In [30]:
print(temp)

[63 47 57 76 70 77 97 35 63 50 67 97 43 85 49 48 52 27 78 60]


In [32]:
name = np.random.choice(['Alex', 'Spar', 'Truk', 'Rist'],20)
print(name)

['Truk' 'Alex' 'Truk' 'Alex' 'Rist' 'Spar' 'Rist' 'Truk' 'Truk' 'Rist'
 'Rist' 'Rist' 'Alex' 'Truk' 'Alex' 'Truk' 'Alex' 'Alex' 'Alex' 'Truk']


In [34]:
random = np.random.choice( [10,11,12,13,14
                           ],20)
print(random)

[10 13 13 12 12 14 11 11 14 12 14 12 10 10 14 11 13 12 14 14]


In [36]:
a = list(zip(temp, name, random))

print(a)

[(63, 'Truk', 10), (47, 'Alex', 13), (57, 'Truk', 13), (76, 'Alex', 12), (70, 'Rist', 12), (77, 'Spar', 14), (97, 'Rist', 11), (35, 'Truk', 11), (63, 'Truk', 14), (50, 'Rist', 12), (67, 'Rist', 14), (97, 'Rist', 12), (43, 'Alex', 10), (85, 'Truk', 10), (49, 'Alex', 14), (48, 'Truk', 11), (52, 'Alex', 13), (27, 'Alex', 12), (78, 'Alex', 14), (60, 'Truk', 14)]


In [42]:
df = pd.DataFrame(data=a, columns=['temp', 'name', 'random'])
df

temp  name  random
0     63  Truk      10
1     47  Alex      13
2     57  Truk      13
3     76  Alex      12
4     70  Rist      12
5     77  Spar      14
6     97  Rist      11
7     35  Truk      11
8     63  Truk      14
9     50  Rist      12
10    67  Rist      14
11    97  Rist      12
12    43  Alex      10
13    85  Truk      10
14    49  Alex      14
15    48  Truk      11
16    52  Alex      13
17    27  Alex      12
18    78  Alex      14
19    60  Truk      14

In [44]:
print(type(a))

<class 'list'>


In [46]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [48]:
df = pd.DataFrame({"temp": temp, "name": name, "random": random})

In [50]:
df

temp  name  random
0     63  Truk      10
1     47  Alex      13
2     57  Truk      13
3     76  Alex      12
4     70  Rist      12
5     77  Spar      14
6     97  Rist      11
7     35  Truk      11
8     63  Truk      14
9     50  Rist      12
10    67  Rist      14
11    97  Rist      12
12    43  Alex      10
13    85  Truk      10
14    49  Alex      14
15    48  Truk      11
16    52  Alex      13
17    27  Alex      12
18    78  Alex      14
19    60  Truk      14

In [52]:
df.head()

temp  name  random
0    63  Truk      10
1    47  Alex      13
2    57  Truk      13
3    76  Alex      12
4    70  Rist      12

In [56]:
df.tail()

temp  name  random
15    48  Truk      11
16    52  Alex      13
17    27  Alex      12
18    78  Alex      14
19    60  Truk      14

In [58]:
df.shape

(20, 3)

In [60]:
df.columns

Index(['temp', 'name', 'random'], dtype='object')

In [62]:
df.name

0     Truk
1     Alex
2     Truk
3     Alex
4     Rist
5     Spar
6     Rist
7     Truk
8     Truk
9     Rist
10    Rist
11    Rist
12    Alex
13    Truk
14    Alex
15    Truk
16    Alex
17    Alex
18    Alex
19    Truk
Name: name, dtype: object

In [64]:
df.random

0     10
1     13
2     13
3     12
4     12
5     14
6     11
7     11
8     14
9     12
10    14
11    12
12    10
13    10
14    14
15    11
16    13
17    12
18    14
19    14
Name: random, dtype: int32

In [66]:
df.temp.describe

<bound method NDFrame.describe of 0     63
1     47
2     57
3     76
4     70
5     77
6     97
7     35
8     63
9     50
10    67
11    97
12    43
13    85
14    49
15    48
16    52
17    27
18    78
19    60
Name: temp, dtype: int32>

In [68]:
df.temp.describe()

count    20.000000
mean     62.050000
std      19.091125
min      27.000000
25%      48.750000
50%      61.500000
75%      76.250000
max      97.000000
Name: temp, dtype: float64

In [70]:
df.name.describe()

count       20
unique       4
top       Truk
freq         7
Name: name, dtype: object

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   temp    20 non-null     int32 
 1   name    20 non-null     object
 2   random  20 non-null     int32 
dtypes: int32(2), object(1)
memory usage: 452.0+ bytes


In [74]:
df

temp  name  random
0     63  Truk      10
1     47  Alex      13
2     57  Truk      13
3     76  Alex      12
4     70  Rist      12
5     77  Spar      14
6     97  Rist      11
7     35  Truk      11
8     63  Truk      14
9     50  Rist      12
10    67  Rist      14
11    97  Rist      12
12    43  Alex      10
13    85  Truk      10
14    49  Alex      14
15    48  Truk      11
16    52  Alex      13
17    27  Alex      12
18    78  Alex      14
19    60  Truk      14

In [78]:
df.values

array([[63, 'Truk', 10],
       [47, 'Alex', 13],
       [57, 'Truk', 13],
       [76, 'Alex', 12],
       [70, 'Rist', 12],
       [77, 'Spar', 14],
       [97, 'Rist', 11],
       [35, 'Truk', 11],
       [63, 'Truk', 14],
       [50, 'Rist', 12],
       [67, 'Rist', 14],
       [97, 'Rist', 12],
       [43, 'Alex', 10],
       [85, 'Truk', 10],
       [49, 'Alex', 14],
       [48, 'Truk', 11],
       [52, 'Alex', 13],
       [27, 'Alex', 12],
       [78, 'Alex', 14],
       [60, 'Truk', 14]], dtype=object)

In [ ]:
# Index