In [1]:
import numpy as np

In [2]:
matrixA = np.matrix([[1,3,5],[2,4,3],[5,6,8]])

In [3]:
matrixA

matrix([[1, 3, 5],
        [2, 4, 3],
        [5, 6, 8]])

In [4]:
matrixA.shape

(3, 3)

In [5]:
matrixB = np.matrix([[3],[5],[7]])

In [6]:
matrixB

matrix([[3],
        [5],
        [7]])

In [8]:
matrixB.shape

(3, 1)

In [9]:
print(matrixA * matrixB)

[[ 53]
 [ 47]
 [101]]


In [ ]:
matrixA *