In [1]:
import numpy as np

In [5]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [7]:
np.arange(18).reshape(3,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [9]:
a = np.arange(18).reshape(3,2,3)

In [11]:
a > 2

array([[[False, False, False],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]]])

In [13]:
a.T

array([[[ 0,  6, 12],
        [ 3,  9, 15]],

       [[ 1,  7, 13],
        [ 4, 10, 16]],

       [[ 2,  8, 14],
        [ 5, 11, 17]]])

In [17]:
b = np.arange(4).reshape(2,2)

In [19]:
print(b)

[[0 1]
 [2 3]]


In [21]:
b.sum()

6

In [23]:
b.sum(axis=0)

array([2, 4])

In [25]:
a.max()

17

In [27]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [29]:
b.max()

3

In [31]:
b

array([[0, 1],
       [2, 3]])

In [33]:
b.argmax()

3